title: Chitransh Sagar 
logo: /assets/img/headshot_circle.png
description: Chitransh Sagar is an accomplished professional with extensive experience in the fields of AI, Apache Spark, and Tableau.
show_downloads: true
theme: jekyll-theme-minimal
