title: Chitransh Sagar 
logo: /Images/GITPIC.jpg
description: Chitransh Sagar is an accomplished professional with extensive experience in the fields of AI, Apache Spark, and Tableau.
show_downloads: true
theme: jekyll-theme-minimal
